spring.application.name=PaymetService

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/payment
spring.datasource.username=postgres
spring.datasource.password=dev
spring.datasouce.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.properties.hibernate.format_sql=true
spring.jpa.datasource-platform=org.hibernate.dialect.PostgreSQLDialect